### ISSUE TITLE
Refactor marquee update

### ISSUE THREAD

**Issue by varffs** [interglobalvision/ondamundial-net#25]
Better to take all values from data on objects and then trigger the update more often

**Comment by varffs** [comment]
@mixcas opinion on this? Would this be an improvement? If not please close this

**Comment by mixcas** [comment]
I don't remember what this issue is about. Do you? Could you expand, @varffs?

**Comment by varffs** [comment]
Checking the codebase the marquee update only seems to trigger on stream online and offline events ~~(which of itself is a bit confusing as surely when the event data is updated the marquee needs to be rebuilt too)~~ The streamonline event triggers on every update of the radio.co status check which is a strange name as clearly the event is not the moment the stream comes online but a continuation of the stream being online. However it does seem that the marquee text is now only set in one place `handleOnlineStream()` so this particular issue is no longer
