### ISSUE TITLE
mobile layout breaks in Safari and FF

### ISSUE THREAD

**Issue by varffs** [interglobalvision/ondamundial-net#32]
![screen shot 2017-07-12 at 19 20 35](https://user-images.githubusercontent.com/845186/28134111-e11b570e-6739-11e7-9df9-1f76d0ae0e68.png)
![screen shot 2017-07-12 at 19 20 14](https://user-images.githubusercontent.com/845186/28134112-e12e90c6-6739-11e7-87d8-f4772f4136a5.png)

The menu drops below the logo line.

**Comment by mikeyrayvon** [comment]
need to add `flex-wrap: nowrap` to row element

**Comment by mikeyrayvon** [comment]
seems that `flex-grow: 1` is treated correctly in chrome, but not in safari

**Comment by varffs** [comment]
This appears to be fixed in master rn
