### ISSUE TITLE
Site.Programacion assumes eventsPosts has data

### ISSUE THREAD

**Issue by varffs** [interglobalvision/ondamundial-net#34]
If `eventsPosts` is empty then `fillEventsObject()` fails

**Comment by varffs** [comment]
@mixcas is this the same as #17 ?

**Comment by varffs** [comment]
@mixcas does https://github.com/interglobalvision/ondamundial-net/blob/737a5bfd9ba10a6795e2f5266a149f99c20968df/src/js/main.js#L207 this fix this issue?

**Comment by mixcas** [comment]
Yes, closing.
