### ISSUE TITLE
Left over placeholder in javascript

### ISSUE THREAD

**Issue by varffs** [interglobalvision/ondamundial-net#41]
This line should be removed/fixed: 

https://github.com/interglobalvision/ondamundial-net/blob/master/src/js/main.js#L814

What should display here when empty? Certainly not that text!

![screen shot 2017-10-09 at 19 25 39](https://user-images.githubusercontent.com/845186/31353573-ff4a575c-ad2a-11e7-88b3-e5463c1cbba8.png)

**Comment by mixcas** [comment]
i think that text is fine
