### ISSUE TITLE
Marquee prefix/showname can be false

### ISSUE THREAD

**Issue by varffs** [interglobalvision/ondamundial-net#42]
![screen shot 2017-10-09 at 19 34 57](https://user-images.githubusercontent.com/845186/31353603-117ede3e-ad2b-11e7-8528-7c778da663ad.png)

I think this line is returning true when the value is false: https://github.com/interglobalvision/ondamundial-net/blob/master/src/js/main.js#L719 Perhaps just needs another check against false?

**Comment by mixcas** [comment]
You are right on this, the api now returns `false` instead of undefined so this condition should get fixed.
