### ISSUE TITLE
SVGs don't come up in production

### ISSUE THREAD

**Issue by mixcas** [interglobalvision/ondamundial-net#47]
I think the function we use to pull svg data is old and doesn't work in newer versions of php

**Comment by mixcas** [comment]
`file_get_contents()` seems more suitable

**Comment by varffs** [comment]
Our function is designed as a replacement for `file_get_contents()` as some shared hosting packages don't have it so. However our function it uses Curl so I kinda doubt that it is depreciated. Do you have any debug info?

One issue I've noticed is that the function makes a full HTTP request (from the server) to the image location, so if there are things in the way of that (like an .htaccess password) it can fail.
